name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  pnpm-version: 10.2.1
  node-version: 20

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm-version }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Install browsers
        run: cd packages/agent && pnpm exec playwright install --with-deps chromium

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('packages/agent/pnpm-lock.yaml') }}

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint
